### ISSUE TITLE
Keep getting connection refused

### ISSUE THREAD

**Issue by devsheva** [wmnnd/nginx-certbot#138]
**Context**:
_Trying to setup HTTPS with Nginx, LetsEncrypt and docker compose in an Amazon Linux 2 EC2 Instance_

I'm trying to run the `init-letsencrypt.sh` script to generate certificates for LetsEncrypt.

My docker compose file is this

```.yml
version: '3'

services:
  # nginx container
  simet-nginx:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped
    volumes:
      - ./data/nginx:/etc/nginx/conf.d
      - ./data/certbot/conf:/etc/letsencrypt # save letsencrypt certificates
      - ./data/certbot/www:/var/www/certbot # autorenew HTTPS certs
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
  certbot:
    image: certbot/certbot:arm64v8-latest
    restart: unless-stopped
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
```

I keep getting 

```
 Certbot failed to authenticate some domains (authenticator: webroot). The Certificate Authority reported these problems:
  Domain: example.org
  Type:   connection
  Detail: 34.246.111.238: Fetching http://example.org/.well-known/acme-challenge/GHdklB3122P6phvmC7rcwS2ByeteMgs43MC04WFu05Y: Connection refused

Hint: The Certificate Authority failed to download the temporary challenge files created by Certbot. Ensure that the listed domains serve their content from the provided --webroot-path/-w and that files created there can be downloaded from the internet.

Some challenges have failed.
```

**Comment by zackaryjing** [comment]
I met this problem too. Have you solved it?

**Comment by st3fus** [comment]
Same here, anyone has a solution?

**Comment by st3fus** [comment]
It works with .com domain, make sure you replace all example.org in both data/nginx/app.conf and init.letsencrypt.sh , but for example, it doesnt work for the same domain thats on .rs

**Comment by KangarooChronicles** [comment]
> It works with .com domain, make sure you replace all example.org in both data/nginx/app.conf and init.letsencrypt.sh , but for example, it doesnt work for the same domain thats on .rs

That explains it for me then.  I'm using a _.au_ address and get the same issue.  Do you know why this occurs?

**Comment by alan-nascimento** [comment]
I was facing the same issue, but it worked for me:

Docker Compose

```yml
version: "3"

services:
    certbot:
        image: certbot/certbot
        restart: unless-stopped
        volumes:
            - ./data/certbot/conf:/etc/letsencrypt
            - ./data/certbot/www:/var/www/certbot
        entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

    nginx:
        image: nginx
        volumes:
            - ./data/nginx:/etc/nginx/conf.d
            - ./data/certbot/conf:/etc/letsencrypt
            - ./data/certbot/www:/var/www/certbot
        ports:
            - "80:80"
            - "443:443"
        depends_on:
            - certbot
            - my-backend
        restart: unless-stopped
        command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

    my-backend:
        image: my-register/my-backend:latest
        ports:
            - "8080:8080"
        restart: unless-stopped
```

NGINX

```yml
server {
    listen 80 default_server;
    server_name my-backend-domain.com.br;
    server_tokens off;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name my-backend-domain.com.br;
    server_tokens off;

    ssl_certificate /etc/letsencrypt/live/my-backend-domain.com.br/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/my-backend-domain.com.br/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    location / {
        proxy_pass http://my-backend-domain:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}
```
IMPORTANT: ensure your DNS is pointed to your instance/IP correctly.
