### ISSUE TITLE
Does not link with Dependent Containers

### ISSUE THREAD

**Issue by judsonjames** [wmnnd/nginx-certbot#14]
I'm running a Docker configuration where I have:
- Django (web application framework)
- Postgres
- Nginx
- Certbot (as per your [guide](https://medium.com/@pentacent/nginx-and-lets-encrypt-with-docker-in-less-than-5-minutes-b4b8a60d3a71))

The Nginx container depends on the Django container for the web app, which worked on my HTTP only implementation. When I modified my Nginx to include Certbot, I get everything saying that the certification works, but the Nginx container no longer links to my Django container.

Below is the relevant docker-compose.yml section
```
#############################################################################
  # Nginx Configurations
  nginx:
    container_name: 'nginx'
    image: nginx:1.15-alpine
    restart: unless-stopped
    volumes:
      - ./data/nginx:/etc/nginx/conf.d
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
      - static_volume:/usr/src/personal_website/static
    ports:
      - "80:80"
      - "443:433"
    depends_on:
      - django
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  #############################################################################
  # Certbot Configurations (SSL)
  certbot:
    container_name: 'certbot'
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
```
