### ISSUE TITLE
multiple subdomains question

### ISSUE THREAD

**Issue by mansard** [wmnnd/nginx-certbot#44]
Been struggling all day with getting this setup to work with two different subdomains which both need to accept https traffic (for a flask site/development site for same) - need to see if anyone has any insight. I'm getting the following errors when the first challenge is attempted while running the script, with some modifications.

On the first cert verification attempt:
```
Waiting for verification...
Challenge failed for domain my.example.domain
http-01 challenge for my.example.domain
Cleaning up challenges
Some challenges have failed.

IMPORTANT NOTES:
 - The following errors were reported by the server:

   Domain: my.example.domain
   Type:   connection
   Detail: Fetching
   http://my.example.domain/.well-known/acme-challenge/Z*****************0:
   Connection refused

	... blah blah A records, etc ...

### Reloading nginx ...
cannot exec in a stopped state: unknown
```

In docker-compose up output - the reason nginx fails above, presumably? 
```
nginx_1 | <timestamp-here> [emerg] 1#1: open() "/etc/letsencrypt/options-ssl-nginx.conf" failed (2: No such file or directory) in /etc/nginx/conf.d/app.conf:22

nginx_1 | nginx: [emerg] open() "/etc/letsencrypt/options-ssl-nginx.conf" failed (2: No such file or directory) in /etc/nginx/conf.d/app.conf:22
```

My Desired Setup: 

- NGINX reverse proxy to accept/redirect all http/s traffic to SSL to both: "my.example.com" and "my-dev.example.com" 
- two basically identical containers, "web" and "web-dev", which are flask apps running on 5000:80 and 5001:80. 
- I want to bring it all up at once with the script and then docker-compose up, issuing separate certs to each (I'm fine with changing it to a single cert for both if that's possible/easier for some reason)

I've tried everything I could find from searching anything remotely related to the issue and suspect it's more a fundamental "not understanding NGINX config" issue on my part than a bug, but I hope someone can help and this question can be a reference for anyone else similarly stuck. I think there might be a solution in the nginx.conf file, having to do with adding some upstream entries, possibly, but I don't quite understand where to begin. 

All my code is below, thank you in advance! 

my nginx.conf
```
server {
    listen 80;
    server_name my.example.domain;
    server_tokens off;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name my.example.domain;
    server_tokens off;

    ssl_certificate /etc/letsencrypt/live/my.example.domain/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/my.example.domain/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    location / {
        proxy_pass  http://web:5000;
        proxy_set_header    Host                $http_host;
        proxy_set_header    X-Real-IP           $remote_addr;
        proxy_set_header    X-Forwarded-For     $proxy_add_x_forwarded_for;
    }
}

server {
    listen 80;
    server_name my-dev.example.domain;
    server_tokens off;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name my-dev.example.domain;
    server_tokens off;

    ssl_certificate /etc/letsencrypt/live/my-dev.example.domain/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/my-dev.example.domain/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    location / {
        proxy_pass  http://web-dev:5001;
        proxy_set_header    Host                $http_host;
        proxy_set_header    X-Real-IP           $remote_addr;
        proxy_set_header    X-Forwarded-For     $proxy_add_x_forwarded_for;
    }
}
```

---------------------------------------------------

my init-letsencrypt.sh
```
#!/bin/bash

domains=(my.example.domain my-dev.example.domain)
rsa_key_size=4096
data_path="./data/certbot"
email="myexample@email.address" # Adding a valid address is strongly recommended
staging=1 # Set to 1 if you're testing your setup to avoid hitting request limits

if [ -d "$data_path" ]; then
  read -p "Existing data found for $domains. Continue and replace existing certificate? (y/N) " decision
  if [ "$decision" != "Y" ] && [ "$decision" != "y" ]; then
    exit
  fi
fi


if [ ! -e "$data_path/conf/options-ssl-nginx.conf" ] || [ ! -e "$data_path/conf/ssl-dhparams.pem" ]; then
  echo "### Downloading recommended TLS parameters ..."
  mkdir -p "$data_path/conf"
  curl -s https://raw.githubusercontent.com/certbot/certbot/master/certbot-nginx/certbot_nginx/tls_configs/options-ssl-nginx.conf > "$data_path/conf/options-ssl-nginx.conf"
  curl -s https://raw.githubusercontent.com/certbot/certbot/master/certbot/ssl-dhparams.pem > "$data_path/conf/ssl-dhparams.pem"
  echo
fi

echo "### Creating dummy certificate for $domains ..."
path="/etc/letsencrypt/live/$domains"
mkdir -p "$data_path/conf/live/$domains"
docker-compose run --rm --entrypoint "\
  openssl req -x509 -nodes -newkey rsa:1024 -days 1\
    -keyout '$path/privkey.pem' \
    -out '$path/fullchain.pem' \
    -subj '/CN=localhost'" certbot
echo


echo "### Starting nginx ..."
docker-compose up --force-recreate -d nginx #tried this both ways
echo

echo "### Deleting dummy certificate for $domains ..."
docker-compose run --rm --entrypoint "\
  rm -Rf /etc/letsencrypt/live/$domains && \
  rm -Rf /etc/letsencrypt/archive/$domains && \
  rm -Rf /etc/letsencrypt/renewal/$domains.conf" certbot
echo


echo "### Requesting Let's Encrypt certificate for $domains ..."
#Join $domains to -d args
domain_args=""
for domain in "${domains[@]}"; do
  domain_args="$domain_args -d $domain"
done

# Select appropriate email arg
case "$email" in
  "") email_arg="--register-unsafely-without-email" ;;
  *) email_arg="--email $email" ;;
esac

# Enable staging mode if needed
if [ $staging != "0" ]; then staging_arg="--staging"; fi

docker-compose run --rm --entrypoint "\
  certbot certonly --webroot -w /var/www/certbot \
    $staging_arg \
    $email_arg \
    $domain_args \
    --rsa-key-size $rsa_key_size \
    --agree-tos \
	--eff-email \  ##"I added this and it should have no weird effect"
    --force-renewal" certbot
echo

echo "### Reloading nginx ..."
docker-compose exec nginx nginx -s reload
```

---------------------------------------------------

my docker-compose
```
version: '3'

services:
  nginx:
    image: nginx:stable-alpine
    restart: unless-stopped
    volumes:
      - ./data/nginx:/etc/nginx/conf.d
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
      - ./data/nginx/file_size.conf:/etc/nginx/file_size.conf # I added this, unrelated?
    ports:
      - "80:80"
      - "443:443"
    links:
      - web
      - web-dev
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"


  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"


  web:
    build:
      context: .
      dockerfile: prod.Dockerfile
    restart: unless-stopped
    volumes:
      - ./data/web:/data/web
    ports:
      - "5000:80"


  web-dev:
    build:
      context: .
      dockerfile: dev.Dockerfile
    restart: unless-stopped
    volumes:
      - ./data/web-dev:/data/web-dev
    ports:
      - "5001:80"
    environment:
      FLASK_ENV: development
```

---------------------------------------------------

my 'web' container dockerfile
```
FROM python:3.7-slim-buster

# handle static files
ENV STATIC_URL /static

# if making changes this should be an absolute path
ENV STATIC_PATH /data/web/static

# set working directory and import /data/web/*
COPY ./data/web /data/web
WORKDIR /data/web

# Make /data/web* available to be imported by Python globally
ENV PYTHONPATH=/data/web

ENV FLASK_APP /data/web/app.py
ENV FLASK_RUN_HOST 0.0.0.0

# install requirements 
COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt

COPY . .
CMD ["flask", "run"]
```

---------------------------------------------------

my 'web-dev' container dockerfile
```
FROM python:3.7-slim-buster

# handle static files
ENV STATIC_URL /static

# if making changes this should be an absolute path
ENV STATIC_PATH /data/web-dev/static

# set working directory and import /data/web-dev/*
COPY ./data/web-dev /data/web-dev
WORKDIR /data-dev/web

# Make /data/web-dev* available to be imported by Python globally
ENV PYTHONPATH=/data/web-dev

ENV FLASK_APP /data/web-dev/app.py
ENV FLASK_RUN_HOST 0.0.0.0

# install requirements 
COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt

COPY . .
CMD ["flask", "run"]
```
